apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-service
spec:
  selector:
    app: jenkins-test
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30667
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-test-vol
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/k8s-jenkins
    server: 10.10.0.217
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-test-vol-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-deployment
  labels:
    app: jenkins-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: jenkins-test-vol-claim
      containers:
      - name: jenkins
        image: jenkins/jenkins
        volumeMounts:
        - name: nfs-volume
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
