apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30661
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: nfs-volume
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/linux-tools/docker/jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.189-alpine
        volumeMounts:
        - name: nfs-volume
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
