apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget-deployment
  labels:
    app: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      volumes:
      - name: nfs-volume-nzbget
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/linux-tools/docker/nzbget/appdata
      - name: nfs-volume-downloads
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/linux-tools/docker/nzbget/downloads
      containers:
      - name: nzbget
        image: linuxserver/nzbget
        volumeMounts:
        - name: nfs-volume-nzbget
          mountPath: /config
        - name: nfs-volume-downloads
          mountPath: /downloads
        ports:
        - containerPort: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget-service
spec:
  selector:
    app: nzbget
  ports:
  - protocol: TCP
    port: 6789
    nodePort: 32405
  type: NodePort
