apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-vol
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/linux-tools/k8s-vol
    server: 10.10.0.217
