apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-docker-deployment
  labels:
    app: pms-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pms-docker
  template:
    metadata:
      labels:
        app: pms-docker
    spec:
      volumes:
      - name: nfs-volume-plex1
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/plex-conf
      - name: nfs-volume-movies
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/Movies
      - name: nfs-volume-tv1
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/TV-Shows
      - name: nfs-volume-tv2
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/TV-Shows1
      - name: nfs-volume-sabnzb
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/sabnzb
      containers:
      - name: pms-docker
        image: plexinc/pms-docker
        volumeMounts:
        - name: nfs-volume-plex1
          mountPath: /config
        - name: nfs-volume-movies
          mountPath: /mnt/movies
        - name: nfs-volume-tv1
          mountPath: /mnt/tv1
        - name: nfs-volume-tv2
          mountPath: /mnt/tv2
        - name: nfs-volume-sabnzb
          mountPath: /sabnzb
        ports:
        - containerPort: 32400
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: pms-docker-service
spec:
  selector:
    app: pms-docker
  ports:
  - protocol: TCP
    port: 32400
    nodePort: 32400
  type: NodePort
