apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd-deployment
  labels:
    app: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      volumes:
      - name: nfs-volume-sabnzb
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/sabnzb-conf
      - name: nfs-volume-downloads
        nfs:
          server: 10.10.0.217 # Change this!
          path: /volume1/sabnzb
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd
        volumeMounts:
        - name: nfs-volume-sabnzb
          mountPath: /config
        - name: nfs-volume-downloads
          mountPath: /mnt/sabnzb
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
spec:
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32401
  type: NodePort
