apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kib-dev-cert
  namespace: the-project
spec:
  secretName: kib-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: kib.the-project.d4ldev.txn2.com
  dnsNames:
  - kib.the-project.d4ldev.txn2.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kib.the-project.d4ldev.txn2.com
    - http01:
        ingressClass: nginx
      domains:
      - kib.the-project.d4ldev.txn2.com
