apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-vip
  labels:
    app: cluster-vip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-vip
  template:
    metadata:
      labels:
        app: cluster-vip
    spec:
      containers:
      - name: cluster-vip
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-vip-service
spec:
  selector:
    app: cluster-vip
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
